//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emmola.Helpers.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emmola.Helpers.i18n.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day after tommorow.
        /// </summary>
        internal static string DAY_AFTER_TOMMORW {
            get {
                return ResourceManager.GetString("DAY_AFTER_TOMMORW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day before yesterday.
        /// </summary>
        internal static string DAY_BEFORE_YESTERDAY {
            get {
                return ResourceManager.GetString("DAY_BEFORE_YESTERDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} days.
        /// </summary>
        internal static string DAYS_AFTER {
            get {
                return ResourceManager.GetString("DAYS_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        internal static string DAYS_AGO {
            get {
                return ResourceManager.GetString("DAYS_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} hours.
        /// </summary>
        internal static string HOURS_AFTER {
            get {
                return ResourceManager.GetString("HOURS_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        internal static string HOURS_AGO {
            get {
                return ResourceManager.GetString("HOURS_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        internal static string JUST_NOW {
            get {
                return ResourceManager.GetString("JUST_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After {0} minutes.
        /// </summary>
        internal static string MINUTES_AFTER {
            get {
                return ResourceManager.GetString("MINUTES_AFTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        internal static string MINUTES_AGO {
            get {
                return ResourceManager.GetString("MINUTES_AGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right now.
        /// </summary>
        internal static string RIGHT_NOW {
            get {
                return ResourceManager.GetString("RIGHT_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tommorow.
        /// </summary>
        internal static string TOMMOROW {
            get {
                return ResourceManager.GetString("TOMMOROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string YESTERDAY {
            get {
                return ResourceManager.GetString("YESTERDAY", resourceCulture);
            }
        }
    }
}
